<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kzoreschedule"
 *
 * Auto generated by Extension Builder 2016-07-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'reSchedule KZO',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Amos Calamida',
	'author_email' => 'amos@calamida.ch',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '4.3.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
